### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by sahilkandpal**
improved nav section

### CODE REVIEW

**Comment by eshanvohra** [comment]
doing for hacktoberfest?

**Comment by eshanvohra** [comment]
first merge my PR in your repo: outsider/devtools

**Comment by sahilkandpal** [comment]
> doing for hacktoberfest?

Yes😎

**Comment by sahilkandpal** [comment]
> first merge my PR in your repo: outsider/devtools

Merged 🙂

**Pull request merged**
